### ISSUE TITLE
Web Development is Literally Awful

### ISSUE THREAD

**Issue by TheLostLambda** [TheLostLambda/syn-zeug#13]
I hate web development. I spent a bunch of time moving to Snowpack, hit a bug when building for production, then learned the project is dead https://github.com/withastro/snowpack/discussions/3864

So time to move on to this week's hot new tech: Vite
https://github.com/sveltejs/vite-plugin-svelte
https://github.com/nshen/vite-plugin-wasm-pack

The WASM plugin looks worse, so I might need to improve that some myself?

I hope the rapture leaves web developers behind.

**Comment by Ta180m** [comment]
I wholeheartedly agree. I don't know how many hours I've wasted on this kind of garbage, but it has to be in the hundreds.

(By the way I stumbled upon this completely at random when I took a look at [GitHub's full list of issues and PRs](https://github.com/pulls?q=) :smiley:)

**Comment by TheLostLambda** [comment]
@Ta180m 
Hahaha :joy: Quite the serendipitous encounter! Glad to know I'm not alone in my suffering :sweat_smile:

Good luck in your future battles against bundlers and thanks for stopping by :vulcan_salute:

**Comment by TheLostLambda** [comment]
The deed is done. Snowpack is dead.
